# Test your FastAPI endpoints

GET http://127.0.0.1:8047/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

POST http://127.0.0.1:8047/auth/register
Content-Type: application/json

{
  "username": "Adirtka",
  "password": "123456"
}

###

POST http://127.0.0.1:8047/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

###

GET http://127.0.0.1:8047/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkODVhMWU1YS1jMzRiLTQ1MzMtODkzNy05YjQ2ZDUxZWNjNTYiLCJ1c2VybmFtZSI6IkFkaXJ0S2EiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzczMTEzNTg0LCJleHAiOjE3NzMxMTcxODR9.UW_qmACwtzi7WqOtXoOqbmnITf8T_TIHUAbSVRRfsbo

###

GET http://127.0.0.1:8047/decks/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5OGIzNzg4Mi1jMzUwLTQyY2QtODFhNC1lZTEyMzRkZmY5ODUiLCJ1c2VybmFtZSI6InRlc3QiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzczMjc2ODI3LCJleHAiOjE3NzMyODA0Mjd9.HQ2LUo198b6tj-pCk7DgoPnFq0_Bm2bJRyWpw1L34ZA

###

PUT http://127.0.0.1:8047/decks/c56ec3f0-03ce-4ffa-8065-62d65df96472
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5OGIzNzg4Mi1jMzUwLTQyY2QtODFhNC1lZTEyMzRkZmY5ODUiLCJ1c2VybmFtZSI6InRlc3QiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzczMjc2ODI3LCJleHAiOjE3NzMyODA0Mjd9.HQ2LUo198b6tj-pCk7DgoPnFq0_Bm2bJRyWpw1L34ZA
Content-Type: application/json

{
  "name" : "aboba"
}