# Test your FastAPI endpoints

GET http://127.0.0.1:8047/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

POST http://127.0.0.1:8047/auth/register
Content-Type: application/json

{
  "username": "Adirtka",
  "password": "123456"
}

###

POST http://127.0.0.1:8047/auth/login
Content-Type: application/json

{
  "username": "3",
  "password": "3"
}

###

GET http://127.0.0.1:8047/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZjdmYTAwZi1kZmYyLTRkZDAtODBlYi1jZDM1MmM0YzMwZWYiLCJ1c2VybmFtZSI6IjMiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzczNTUyODg5LCJleHAiOjE3NzM1NTY0ODl9.NJcvqzjMjnhyqg5nBHgix0WAI9yLfOvTI_eWa1kKBgM
###

GET http://127.0.0.1:8047/decks/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZjdmYTAwZi1kZmYyLTRkZDAtODBlYi1jZDM1MmM0YzMwZWYiLCJ1c2VybmFtZSI6IjMiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzczNTUyODg5LCJleHAiOjE3NzM1NTY0ODl9.NJcvqzjMjnhyqg5nBHgix0WAI9yLfOvTI_eWa1kKBgM

###

PUT http://127.0.0.1:8047/decks/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZjdmYTAwZi1kZmYyLTRkZDAtODBlYi1jZDM1MmM0YzMwZWYiLCJ1c2VybmFtZSI6IjMiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzczNTUyODg5LCJleHAiOjE3NzM1NTY0ODl9.NJcvqzjMjnhyqg5nBHgix0WAI9yLfOvTI_eWa1kKBgM
Content-Type: application/json

{
  "name" : "aboba"
}

###

GET http://127.0.0.1:8047/review/due
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZjdmYTAwZi1kZmYyLTRkZDAtODBlYi1jZDM1MmM0YzMwZWYiLCJ1c2VybmFtZSI6IjMiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzczNTUyODg5LCJleHAiOjE3NzM1NTY0ODl9.NJcvqzjMjnhyqg5nBHgix0WAI9yLfOvTI_eWa1kKBgM

###

GET http://127.0.0.1:8047/stats/overview
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZjdmYTAwZi1kZmYyLTRkZDAtODBlYi1jZDM1MmM0YzMwZWYiLCJ1c2VybmFtZSI6IjMiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzczNTUyODg5LCJleHAiOjE3NzM1NTY0ODl9.NJcvqzjMjnhyqg5nBHgix0WAI9yLfOvTI_eWa1kKBgM

###

GET http://127.0.0.1:8047/stats/last-review-activity?days=30
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZjdmYTAwZi1kZmYyLTRkZDAtODBlYi1jZDM1MmM0YzMwZWYiLCJ1c2VybmFtZSI6IjMiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzczNTUyODg5LCJleHAiOjE3NzM1NTY0ODl9.NJcvqzjMjnhyqg5nBHgix0WAI9yLfOvTI_eWa1kKBgM

###

GET http://127.0.0.1:8047/stats/review-history?days=30
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZjdmYTAwZi1kZmYyLTRkZDAtODBlYi1jZDM1MmM0YzMwZWYiLCJ1c2VybmFtZSI6IjMiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzczNTUyODg5LCJleHAiOjE3NzM1NTY0ODl9.NJcvqzjMjnhyqg5nBHgix0WAI9yLfOvTI_eWa1kKBgM

###

GET http://127.0.0.1:8047/stats/due-forecast?days=14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZjdmYTAwZi1kZmYyLTRkZDAtODBlYi1jZDM1MmM0YzMwZWYiLCJ1c2VybmFtZSI6IjMiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzczNTUyODg5LCJleHAiOjE3NzM1NTY0ODl9.NJcvqzjMjnhyqg5nBHgix0WAI9yLfOvTI_eWa1kKBgM

###

GET http://127.0.0.1:8047/stats/decks/progress
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZjdmYTAwZi1kZmYyLTRkZDAtODBlYi1jZDM1MmM0YzMwZWYiLCJ1c2VybmFtZSI6IjMiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzczNTUyODg5LCJleHAiOjE3NzM1NTY0ODl9.NJcvqzjMjnhyqg5nBHgix0WAI9yLfOvTI_eWa1kKBgM
