"""Add cards and cards progress

Revision ID: f04799371111
Revises: 47b403152a18
Create Date: 2026-03-12 21:04:48.366226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04799371111'
down_revision: Union[str, Sequence[str], None] = '47b403152a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('front_main_text', sa.Text(), nullable=False),
    sa.Column('front_sub_text', sa.Text(), nullable=True),
    sa.Column('back_main_text', sa.Text(), nullable=False),
    sa.Column('back_sub_text', sa.Text(), nullable=True),
    sa.Column('front_image_id', sa.UUID(), nullable=True),
    sa.Column('front_audio_id', sa.UUID(), nullable=True),
    sa.Column('back_image_id', sa.UUID(), nullable=True),
    sa.Column('back_audio_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['back_audio_id'], ['media_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['back_image_id'], ['media_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['front_audio_id'], ['media_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['front_image_id'], ['media_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_deck_id'), 'cards', ['deck_id'], unique=False)
    op.create_table('card_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('ease', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('last_answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_answer_correct', sa.Boolean(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', name='uq_card_progress_user_card')
    )
    op.create_index(op.f('ix_card_progress_card_id'), 'card_progress', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_progress_user_id'), 'card_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_progress_user_id'), table_name='card_progress')
    op.drop_index(op.f('ix_card_progress_card_id'), table_name='card_progress')
    op.drop_table('card_progress')
    op.drop_index(op.f('ix_cards_deck_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_table('media_files')
    # ### end Alembic commands ###
